version: 2.1
jobs:
  check:
    docker:
    - image: hashicorp/terraform:0.11.11
    working_directory: /go/src/github.com/joshdk/terraform-gke-kubeconfig
    steps:
    - checkout
    - run:
        name: Check formatting
        command: terraform fmt -list -check module

  build:
    docker:
    - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/joshdk/terraform-gke-kubeconfig
    steps:
    - checkout
    - run:
        name: Build artifacts
        working_directory: artifacts
        command: |
          version="$(git describe --tags)"
          tar -czvf module.tgz -C ../module .
    - run:
        name: Checksum artifacts
        working_directory: artifacts
        command: sha256sum --binary --tag * | tee checksums.txt
    - store_artifacts:
        path: artifacts
        destination: /artifacts
    - persist_to_workspace:
        root: .
        paths:
        - artifacts

workflows:
  version: 2
  build:
    jobs:
    - check
    - build
