version: 2.1
jobs:
  check:
    docker:
    - image: hashicorp/terraform:0.11.11
    working_directory: /go/src/github.com/joshdk/terraform-gke-kubeconfig
    steps:
    - checkout
    - run:
        name: Install tools
        working_directory: /tmp
        command: |
          apk add --no-cache make
          wget -q https://github.com/segmentio/terraform-docs/releases/download/v0.6.0/terraform-docs-v0.6.0-linux-amd64
          install terraform-docs-v0.6.0-linux-amd64 /usr/bin/terraform-docs
    - run:
        name: Check formatting
        command: make format-check
    - run:
        name: Check that docs are up to date
        command: make docs-check

  build:
    docker:
    - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/joshdk/terraform-gke-kubeconfig
    steps:
    - checkout
    - run:
        name: Build artifacts
        command: make artifact
    - store_artifacts:
        path: artifacts
        destination: /artifacts
    - persist_to_workspace:
        root: .
        paths:
        - artifacts

workflows:
  version: 2
  build:
    jobs:
    - check
    - build
